#!/usr/bin/env node
/**
 * Writes apps/web/public/third-party-notices.txt: the licence and copyright
 * notice of every font and npm package Morrri ships, served at
 * /third-party-notices.txt and linked from section 17 of the Terms.
 *
 * MIT, BSD, ISC and Apache all ask that their notice travel with copies of the
 * software, and the browser bundle is a copy. The SIL Open Font License asks
 * the same of the font files `next/font` self-hosts.
 *
 * Run it after changing dependencies, where node_modules actually exist. In
 * this repo that is inside a container, because the host has no install:
 *
 *   npm run notices   (runs it inside the web container)
 *
 * It reads package-lock.json to find the production dependency closure of the
 * web app and the shared package, then takes each package's licence text from
 * its own LICENSE file. The API is left out on purpose: it runs only on our
 * servers and is never handed to anyone, and these licences attach their
 * notice duty to copies that are distributed. A package that is in the lockfile but not
 * installed (another platform's native binary) is skipped, since it never
 * ships from this machine's build either.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'apps/web/public/third-party-notices.txt');
const WORKSPACES = ['apps/web', 'packages/shared'];

/** Every typeface `next/font/google` downloads, with the OFL file Google Fonts publishes for it. */
const FONTS = [
  { name: 'Geist', file: 'geist.txt' },
  { name: 'Geist Mono', file: 'geistmono.txt' },
  { name: 'Fraunces', file: 'fraunces.txt' },
  { name: 'Noto Sans KR', file: 'notosanskr.txt' },
  { name: 'Noto Sans SC', file: 'notosanssc.txt' },
];

const lock = JSON.parse(fs.readFileSync(path.join(ROOT, 'package-lock.json'), 'utf8')).packages;

/** Node's resolution: look in each ancestor's node_modules, nearest first. */
function resolve(fromKey, name) {
  let dir = fromKey;
  for (;;) {
    const key = `${dir ? `${dir}/` : ''}node_modules/${name}`;
    if (lock[key]) return key;
    if (!dir) return null;
    const i = dir.lastIndexOf('/node_modules/');
    dir = i >= 0 ? dir.slice(0, i) : '';
  }
}

const seen = new Map();
function walk(key) {
  const entry = lock[key];
  if (!entry) return;
  const deps = { ...entry.dependencies, ...entry.optionalDependencies, ...entry.peerDependencies };
  for (const name of Object.keys(deps)) {
    const dep = resolve(key, name);
    if (!dep || seen.has(dep) || lock[dep].dev) continue;
    seen.set(dep, lock[dep]);
    walk(dep);
  }
}
WORKSPACES.forEach(walk);

const LICENSE_FILE = /^(licen[cs]e|copying|notice)(\.(md|txt|markdown))?$|^licen[cs]e[-_.]/i;

const groups = new Map(); // licence text -> { spdx, packages[] }
let skipped = 0;
for (const [key, entry] of seen) {
  const dir = path.join(ROOT, entry.link ? entry.resolved : key);
  if (!fs.existsSync(dir)) {
    skipped++;
    continue;
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
  if (pkg.name?.startsWith('@reserivo/')) continue;
  const spdx =
    (typeof pkg.license === 'string' ? pkg.license : pkg.license?.type) ??
    pkg.licenses?.map((l) => l.type ?? l).join(' OR ') ??
    entry.license ??
    'UNKNOWN';
  const files = fs.readdirSync(dir).filter((f) => LICENSE_FILE.test(f)).sort();
  const text = files.length
    ? files.map((f) => fs.readFileSync(path.join(dir, f), 'utf8').replace(/\r\n/g, '\n').trim()).join('\n\n')
    : `No licence file is included in this package. Its package.json declares the licence as ${spdx}.`;
  const g = groups.get(text) ?? { spdx, packages: [] };
  g.packages.push(`${pkg.name}@${pkg.version}`);
  groups.set(text, g);
}

const RULE = '-'.repeat(78);
const out = [
  'Third-party notices for Morrri',
  '',
  'The Morrri website is built with the typefaces and open-source packages',
  'listed below. Each is used under its own licence, reproduced here as its',
  'authors require.',
  'This file is generated by scripts/third-party-notices/generate.cjs.',
  '',
  '='.repeat(78),
  'TYPEFACES',
  '='.repeat(78),
];
for (const font of FONTS) {
  const text = fs.readFileSync(path.join(__dirname, 'fonts', font.file), 'utf8').replace(/\r\n/g, '\n').trim();
  out.push('', RULE, font.name, RULE, '', text);
}
out.push('', '='.repeat(78), 'SOFTWARE PACKAGES', '='.repeat(78));
const sorted = [...groups.entries()].sort(([, a], [, b]) => a.packages[0].localeCompare(b.packages[0]));
for (const [text, g] of sorted) {
  g.packages.sort();
  out.push('', RULE, `${g.packages.join(', ')}`, `Licence: ${g.spdx}`, RULE, '', text);
}
out.push('');

fs.writeFileSync(OUT, out.join('\n'));
const count = [...groups.values()].reduce((n, g) => n + g.packages.length, 0);
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${FONTS.length} typefaces, ${count} packages (${skipped} not installed, skipped).`);
